spring.application.name=notes-back
spring.profiles.active=local

spring.datasource.url=jdbc:postgresql://localhost:5432/notes-db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false